common:
  wandb_mode: online
  test: true
  
  n_envs: 8
  eval_envs: 16

  steps_per_epoch: 1000
  buffer_size: 100000
  batch_size: 32
  eps_anneal_steps: 75000
  gamma: 0.98
  lr: 0.00025
  epochs: 90
  eval_freq: 1
  seed: 0
  max_eval_steps: 500
  manhatten_fac: 0.1
  eps: 0.1
  min_eps: 0.05
  run_group: dueling
  
runs:
  - run_name: "normal"
    backbone: "normal"
    buffer_alpha: 0.0
    buffer_beta: 0.0
    incr_buffbeta: 0.0
  - run_name: "dueling"
    backbone: "dueling"
    buffer_alpha: 0.0
    buffer_beta: 0.0
    incr_buffbeta: 0.0
  - run_name: "normal_prioritized_light"
    backbone: "normal"
    buffer_alpha: 0.4
    buffer_beta: 0.4
    incr_buffbeta: 0.000015

  - run_name: "normal_prioritized_aggressive"
    backbone: "normal"
    buffer_alpha: 0.6
    buffer_beta: 0.4
    incr_buffbeta: 0.000015

  